HafizBackpack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls'))
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import get_product_json
from main.views import add_product_ajax
from main.views import increment, decrement, increment_ajax, decrement_ajax, delete_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('increment/<int:products>', increment, name='increment'),
    path('decrement/<int:products>', decrement, name='decrement'),
    path('increment-ajax/<int:id>/', increment_ajax, name="increment_ajax"),
    path('decrement-ajax/<int:id>/', decrement_ajax, name="decrement_ajax"),
    path('delete-ajax/<int:id>/', delete_ajax, name="delete_ajax"),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    fruit_type = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_discount = models.BooleanField(default= False)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description","fruit_type", "is_discount"]

main/views.py
import datetime
import json
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseNotFound
from django.urls import reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    counter = products.count
    if request.method == 'POST':
        if 'increment' in request.POST:
            increment(request, products)
            return HttpResponseRedirect(reverse('main:show_main'))
        elif 'decrement' in request.POST:
            decrement(request, products)
            return HttpResponseRedirect(reverse('main:show_main'))
        elif 'delete' in request.POST:
            delete(request, products)
            return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'name': request.user.username,
        'class': 'PBP KI', # Your PBP Class
        'products': products,
        'counter' : counter,
        'last_login': request.COOKIES['last_login'],

    }

    return render(request, "main.html", context)

@login_required(login_url='/login')
def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

@login_required(login_url='/login')
def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/login')
def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
@csrf_exempt
def increment(request, products):
    product_id = request.POST.get('increment')
    product = Product.objects.get(id=product_id)
    product.amount += 1
    product.save()

@login_required(login_url='/login')
def decrement(request, products):
    product_id = request.POST.get('decrement')
    product = products.get(id=product_id)
    product.amount -= 1
    product.save()

@login_required(login_url='/login')
def delete(request, products):
    product_id = request.POST.get('delete')
    product = products.get(id=product_id)
    product.delete()

@login_required(login_url='/login')
def edit_product(request, id):
    product = Product.objects.get(pk=id)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:show_main'))
    else:
        form = ProductForm(instance=product)

    context = {'form': form}
    return render(request, "edit_product.html", context)

@login_required(login_url='/login')
def delete_product(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        fruit_type = request.POST.get("fruit_type")
        user = request.user
        is_discount = request.POST.get("is_discount")

        new_product = Product(name=name, amount=amount, description=description, fruit_type=fruit_type, user=user, is_discount=is_discount)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
@login_required(login_url='/login')
def increment_ajax(request, id):
    item = Product.objects.get(pk=id)
    item.amount += 1
    item.save()
    return JsonResponse({"message": "Quantity incremented successfully"})

@csrf_exempt
def decrement_ajax(request, id):
    item = Product.objects.get(pk=id)
    item.amount -= 1
    item.save()
    return JsonResponse({"message": "Quantity decremented successfully"})

@csrf_exempt
def delete_ajax(request, id):
    item = Product.objects.get(pk=id)
    item.delete()
    return JsonResponse({"message": "Product removed successfully"})


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
            fruit_type = data["fruit_type"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<div class="text-center">
    <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
        ADD NEW <span class="underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-600">FRUIT</span>
    </h1>
</div>

<div class="min-h-screen flex justify-center items-center">
    <form method="POST">
        {% csrf_token %}
        <div class="w-screen max-w-xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
            <h5 class="text-xl font-medium text-gray-900 dark:text-white">Add a New Product</h5>
            
            <!-- Product Name Field -->
            <div class="mb-4">
                <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Product Name</label>
                <input type="text" name="name" id="id_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Product Name" required>
            </div>
            
            <!-- Amount Field -->
            <div class="mb-4">
                <label for="id_amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
                <input type="number" name="amount" id="id_amount" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Amount" required>
            </div>
            
            <!-- Description Field -->
            <div class="mb-4">
                <label for="id_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                <div class="max-h-48 overflow-y-auto">
                    <textarea name="description" id="id_description" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Description" rows="4" required></textarea>
                </div>
            </div>
            
            <!-- Fruit Type Field -->
            <div class="mb-4">
                <label for="id_fruit_type" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fruit Type</label>
                <select name="fruit_type" id="id_fruit_type" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                    <option value="">Select Fruit Type</option>
                    <option value="Logia">Logia</option>
                    <option value="Paramecia">Paramecia</option>
                    <option value="Zoan">Zoan</option>
                    <option value="Mythical Zoan">Mythical Zoan</option>
                </select>
            </div>
            
            <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add Product</button>
        </div>
    </form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<div class="text-center">
    <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
        EDIT <span class="underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-600">FRUITS</span>
    </h1>
</div>

<div class="min-h-screen flex justify-center items-center">
    <form method="POST">
        {% csrf_token %}
        <div class="w-screen max-w-xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
            <h5 class="text-xl font-medium text-gray-900 dark:text-white">Edit Product</h5>
            
            <!-- Product Name Field with current value -->
            <div class="mb-4">
                <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Product Name</label>
                <input type="text" name="name" id="id_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Product Name" value="{{ form.instance.name }}" required>
            </div>
            
            <!-- Amount Field with current value -->
            <div class="mb-4">
                <label for="id_amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
                <input type="number" name="amount" id="id_amount" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Amount" value="{{ form.instance.amount }}" required>
            </div>
            
            <!-- Description Field with current value -->
            <div class="mb-4">
                <label for="id_description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                <div class="max-h-48 overflow-y-auto">
                    <textarea name="description" id="id_description" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Description" rows="4" required>{{ form.instance.description }}</textarea>
                </div>
            </div>
            
            <!-- Fruit Type Field with current value -->
            <div class="mb-4">
                <label for="id_fruit_type" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fruit Type</label>
                <select name="fruit_type" id="id_fruit_type" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                    <option value="">Select Fruit Type</option>
                    <option value="Logia" {% if form.instance.fruit_type == 'Logia' %}selected{% endif %}>Logia</option>
                    <option value="Paramecia" {% if form.instance.fruit_type == 'Paramecia' %}selected{% endif %}>Paramecia</option>
                    <option value="Zoan" {% if form.instance.fruit_type == 'Zoan' %}selected{% endif %}>Zoan</option>
                    <option value="Mythical Zoan" {% if form.instance.fruit_type == 'Mythical Zoan' %}selected{% endif %}>Mythical Zoan</option>
                </select>
            </div>
            
            <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Edit Product</button>
        </div>
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class = "login flex h-screen justify-center items-center">

    <form method="POST" action="">
        {% csrf_token %}

            <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
                <form class="space-y-6" action="#">
                    <h5 class="text-xl font-medium text-gray-900 dark:text-white">LOGIN</h5>
                    <div>
                        <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Username</label>
                        <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Username" required>
                    </div>
                    <div class="pb-4">
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
                        <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                    </div>

                    <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Login Now!</button>
                    <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                       <p> Don't have an account yet? <a class="text-blue-700 hover:underline dark:text-blue-500" href="{% url 'main:register' %}">Register Now!</a></p>
                    </div>
                </form>
            </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

main/templates/navbar.html
{% load static %}
{% block content %}


<nav class="bg-white dark:bg-gray-900 w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">HAFIZ BACKPACK</span>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-backpack4-fill" viewBox="0 0 16 16">
            <path d="M8 0a2 2 0 0 0-2 2H3.5a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h4v.5a.5.5 0 0 0 1 0V7h4a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H10a2 2 0 0 0-2-2Zm1 2a1 1 0 0 0-2 0h2Zm-4 9v2h6v-2h-1v.5a.5.5 0 0 1-1 0V11H5Z"/>
            <path d="M14 7.599A2.986 2.986 0 0 1 12.5 8H9.415a1.5 1.5 0 0 1-2.83 0H3.5A2.986 2.986 0 0 1 2 7.599V14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7.599ZM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-3Z"/>
          </svg>
    </div>
</nav>

{% endblock %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
{% include 'navbar.html' %}
<div class = "login flex h-screen justify-center items-center">

   

    <form method="POST" action="">
        {% csrf_token %}
            
            <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
                <form class="space-y-6" action="#">
                    <h5 class="text-xl font-medium text-gray-900 dark:text-white">REGISTER</h5>
                    <div>
                        <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your Username</label>
                        <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="Username" required>
                    </div>
                    <div class="pb-1">
                        <label for="password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
                        <input type="password" name="password1" id="password1" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                    </div>

                    <div class="pb-4">
                        <label for="password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm password</label>
                        <input type="password" name="password2" id="password2" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required>
                    </div>
            
                    <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Regsiter Now!</button>
                    <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                       <p> Already have an account? <a class="text-blue-700 hover:underline dark:text-blue-500" href="{% url 'main:login' %}">Login Now!</a></p>
                    </div>
                </form>
            </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     

</div>

{% comment %} <div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>   {% endcomment %}

{% endblock content %}